package com.aws.iot.evergreen.ipc.services.cli;

public enum CliClientOpCodes {
    GET_COMPONENT_DETAILS,
    LIST_COMPONENTS,
    RESTART_COMPONENT,
    STOP_COMPONENT,
    CREATE_LOCAL_DEPLOYMENT,
    UPDATE_RECIPES_AND_ARTIFACTS,
    GET_LOCAL_DEPLOYMENT_STATUS,
    LIST_LOCAL_DEPLOYMENTS
}
