name: Java CI

on:
  push:
    branches:
      - master
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: [self-hosted, Linux, greengrass]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.head_ref}}
        if: github.event_name == 'pull_request'
      - uses: actions/checkout@v2
        with:
          ref: master
        if: github.event_name == 'push'
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Publish with Maven
        run: mvn -ntp --settings settings.xml clean deploy -Devergreen-ipc-java-sdk-repository-url=${{ secrets.evergreen_ipc_java_sdk_dev_snapshot_url }}
      - name: Convert Jacoco to Cobertura
        run: python3 .github/scripts/cover2cover.py target/jacoco-report/jacoco.xml src/main/java > target/jacoco-report/cobertura.xml
      - name: cobertura-report
        uses: 5monkeys/cobertura-action@master
        with:
          # The GITHUB_TOKEN for this repo
          repo_token: ${{ github.token }}
          # Path to the cobertura file.
          path: target/jacoco-report/cobertura.xml
          # If files with 100% should be skipped from report.
          skip_covered: false
          # Minimum allowed coverage percentage as an integer.
          minimum_coverage: 60
          # Show line rate as specific column.
          show_line: true
          # Show branch rate as specific column.
          show_branch: true
          # Use class names instead of the filename
          show_class_names: true
      - name: Upload Coverage
        uses: actions/upload-artifact@v1.0.0
        with:
          name: Coverage Report
          path: target/jacoco-report
      - name: GitHub Actions Artifact Cleaner
        uses: glassechidna/artifact-cleaner@v2
        with:
          # Specify a minimum size of artifacts to delete in bytes. Artifacts smaller than this won't be deleted.
          minimumDeletionSize: 0 # optional, default is 0
          # Only delete artifacts older than this, measured in seconds.
          minimumAge: 5184000 # optional, default is 0. Set to 5.184e+6 (60 days)
