name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build
        run: mvn -U -ntp clean verify
      - name: Upload Coverage
        uses: actions/upload-artifact@v1.0.0
        with:
          name: Coverage Report
          path: target/jacoco-report
      - name: Convert Jacoco to Cobertura
        run: python3 .github/scripts/cover2cover.py target/jacoco-report/jacoco.xml src/main/java > target/jacoco-report/cobertura.xml
      - name: Save PR number
        run: |
          mkdir -p ./pr/jacoco-report
          echo ${{ github.event.number }} > ./pr/NR
          echo ${{ github.event.pull_request.head.sha }} > ./pr/SHA

          cp target/jacoco-report/cobertura.xml ./pr/jacoco-report/cobertura.xml
        if: github.event_name == 'pull_request'
      - name: Upload files
        uses: actions/upload-artifact@v2
        with:
          name: pr
          path: pr/
        if: github.event_name == 'pull_request'
